/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.47
 * Generated at: 2020-05-17 14:33:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.center;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class imooc_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1589425509887L));
    _jspx_dependants.put("jar:file:/E:/javaSpring/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/wjj-video-admin-mng/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153356282000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("        \n");
      out.write("<style>\n");
      out.write("\n");
      out.write(".desc {\n");
      out.write("\tline-height:18px;\n");
      out.write("\ttext-indent:2em;\n");
      out.write("}\n");
      out.write("\n");
      out.write("</style>\n");
      out.write("        \n");
      out.write("\t<div class=\"page-bar\">\n");
      out.write("\t    <ul class=\"page-breadcrumb\">\n");
      out.write("\t        <li>\n");
      out.write("\t            <a href=\"index.html\">首页</a>\n");
      out.write("\t        </li>\n");
      out.write("\t    </ul>\n");
      out.write("\t</div>\n");
      out.write("\t\n");
      out.write("\t<h1 class=\"page-title\"> 狗狗短视频后台管理系统 </h1>\n");
      out.write("                        \n");
      out.write("\t<div class=\"clearfix\"></div>\n");
      out.write("        \n");
      out.write("\t<div class=\"row\">\n");
      out.write("\t    <div class=\"col-lg-6 col-xs-12 col-sm-12\">\n");
      out.write("\t        \n");
      out.write("\t        <div class=\"portlet light portlet-fit bordered\">\n");
      out.write("\t            <div class=\"portlet-title\">\n");
      out.write("\t                <div class=\"caption\">\n");
      out.write("\t                    <i class=\"icon-microphone font-dark hide\"></i>\n");
      out.write("\t                    <span class=\"caption-subject bold font-dark uppercase\"> 平台技术简介</span>\n");
      out.write("\t                    <span class=\"caption-helper\">小程序后台接口  + 短视频后台管理</span>\n");
      out.write("\t                </div>\n");
      out.write("\t            </div>\n");
      out.write("\t            <div class=\"portlet-body\">\n");
      out.write("\t                <div class=\"row\">\n");
      out.write("\t                    <div class=\"col-md-12\">\n");
      out.write("\t                        <div class=\"mt-widget-3\" style=\"padding-top: 15px;\">\n");
      out.write("\t                        \t<p class=\"desc\"><font style=\"font-size: 16px;\"><b>小程序api - 技术选型：</b></font></p>\n");
      out.write("\t                        \t<p class=\"desc\">1、核心框架：Spring Framework 4.3.14.RELEASE</p>\n");
      out.write("\t                        \t<p class=\"desc\">2、SpringBoot：1.5.10.RELEASE</p>\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"desc\">3、持久层框架：MyBatis 3.4.5 + pagehelper 5.1.2</p>\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"desc\">4、MariaDB 10.2.6</p>\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"desc\">5、数据库连接池：阿里巴巴 Druid 1.1.0</p>\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"desc\">6、zookeeper：3.4.11</p>\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"desc\">7、spring-data-redis：1.8.7.RELEASE</p>\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"desc\">8、swagger2：2.4.0</p>\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"desc\">9、FFmpeg：2.0.1.1</p>\n");
      out.write("\t                        </div>\n");
      out.write("\t                    </div>\n");
      out.write("\t                </div>\n");
      out.write("\t                \n");
      out.write("\t                <div class=\"row\" style=\"margin-top: 15px;\">\n");
      out.write("\t                    <div class=\"col-md-12\">\n");
      out.write("\t                        <div class=\"mt-widget-3\" style=\"padding-top: 15px;\">\n");
      out.write("\t                        \t<p class=\"desc\"><font style=\"font-size: 16px;\"><b>短视频后台 - 技术选型：</b></font></p>\n");
      out.write("\t                        \t<p class=\"desc\">1、核心框架：Spring Framework 4.3.8.RELEASE</p>\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"desc\">2、持久层框架：MyBatis 3.2.8 + pagehelper 4.1.3</p>\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"desc\">3、MariaDB 10.2.6</p>\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"desc\">4、数据库连接池：阿里巴巴 Druid 1.1.0</p>\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"desc\">5、jackson：2.7.4</p>\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"desc\">6、slf4j：1.7.21</p>\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"desc\">7、zookeeper：3.4.11</p>\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"desc\">8、前端框架：Bootstrap + Jquery</p>\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"desc\">9、前端分页组件：jqGrid</p>\n");
      out.write("\t                        </div>\n");
      out.write("\t                    </div>\n");
      out.write("\t                </div>\n");
      out.write("\t                \n");
      out.write("<!-- \t                <div class=\"row\" style=\"margin-top: 15px;\"> -->\n");
      out.write("<!-- \t                    <div class=\"col-md-12\"> -->\n");
      out.write("<!-- \t                        <div class=\"mt-widget-3\" style=\"padding-top: 15px;\"> -->\n");
      out.write("<!-- \t                        \t彩蛋：分布式集群架构的演变 -->\n");
      out.write("<!-- \t                        </div> -->\n");
      out.write("<!-- \t                    </div> -->\n");
      out.write("<!-- \t                </div> -->\n");
      out.write("\t            </div>\n");
      out.write("\t        </div>\n");
      out.write("\t        \n");
      out.write("\t    </div>\n");
      out.write("\t    \n");
      out.write("\t    <div class=\"col-lg-6 col-xs-12 col-sm-12\">\n");
      out.write("\t        <div class=\"portlet light portlet-fit bordered\">\n");
      out.write("\t            <div class=\"portlet-title\">\n");
      out.write("\t                <div class=\"caption\">\n");
      out.write("\t                    <i class=\"icon-microphone font-dark hide\"></i>\n");
      out.write("\t                    <span class=\"caption-subject bold font-dark uppercase\"> 慕课网</span>\n");
      out.write("\t                    <span class=\"caption-helper\">视频推荐</span>\n");
      out.write("\t                </div>\n");
      out.write("\t            </div>\n");
      out.write("\t            <div class=\"portlet-body \">\n");
      out.write("\t            \t<div class=\"row \">\n");
      out.write("\t                    <div class=\"col-md-4 \">\n");
      out.write("\t                        <img src=\"");
      out.print(request.getContextPath() );
      out.write("/static/pages/img/course/springboot.jpg\" width=\"233px\" class=\"img-responsive\"/>\n");
      out.write("\t                    </div>\n");
      out.write("\t                    <div class=\"col-md-8 \" >\n");
      out.write("\t                    \t<h4><a href=\"https://www.imooc.com/comment/956\" target=\"_blank\">《SpringBoot开发常用技术整合》</a></h4>\n");
      out.write("\t                    </div>\n");
      out.write("\t                </div>\n");
      out.write("\t                <div class=\"row \" style=\"margin-top: 10px;\">\n");
      out.write("\t                    <div class=\"col-md-4 \">\n");
      out.write("\t                        <img src=\"");
      out.print(request.getContextPath() );
      out.write("/static/pages/img/course/zookeeper.jpg\" width=\"233px\" class=\"img-responsive\"/>\n");
      out.write("\t                    </div>\n");
      out.write("\t                    <div class=\"col-md-8 \" >\n");
      out.write("\t                    \t<h4><a href=\"https://coding.imooc.com/class/201.html\" target=\"_blank\">《ZooKeeper分布式专题与Dubbo微服务入门》</a></h4>\n");
      out.write("\t                    </div>\n");
      out.write("\t                </div>\n");
      out.write("\t            </div>\n");
      out.write("\t        </div>\n");
      out.write("\t    </div>\n");
      out.write("\t</div>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
