/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.47
 * Generated at: 2020-05-17 14:29:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.center;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-4.3.8.RELEASE.jar", Long.valueOf(1589421230974L));
    _jspx_dependants.put("jar:file:/E:/javaSpring/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/wjj-video-admin-mng/WEB-INF/lib/spring-webmvc-4.3.8.RELEASE.jar!/META-INF/spring.tld", Long.valueOf(1492496852000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("  \n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("\t<meta charset=\"utf-8\" />\n");
      out.write("    <title>短视频后台管理系统</title>\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("    <meta content=\"width=device-width, initial-scale=1\" name=\"viewport\" />\n");
      out.write("    <meta content=\"leechenxiang\" name=\"author\" />\n");
      out.write("    \n");
      out.write("    <link href=\"");
      out.print(request.getContextPath() );
      out.write("/static/global/plugins/font-awesome/css/font-awesome.min.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("    <link href=\"");
      out.print(request.getContextPath() );
      out.write("/static/global/plugins/simple-line-icons/simple-line-icons.min.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("    <link href=\"");
      out.print(request.getContextPath() );
      out.write("/static/global/plugins/bootstrap/css/bootstrap.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("\t<link href=\"");
      out.print(request.getContextPath() );
      out.write("/static/global/plugins/bootstrap-switch/css/bootstrap-switch.min.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("    <!-- END GLOBAL MANDATORY STYLES -->\n");
      out.write("    <!-- BEGIN PAGE LEVEL PLUGINS -->\n");
      out.write("    <link href=\"");
      out.print(request.getContextPath() );
      out.write("/static/global/plugins/select2/css/select2.min.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("    <link href=\"");
      out.print(request.getContextPath() );
      out.write("/static/global/plugins/select2/css/select2-bootstrap.min.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("    <link href=\"");
      out.print(request.getContextPath() );
      out.write("/static/global/plugins/bootstrap-sweetalert/sweetalert.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("    <!-- END PAGE LEVEL PLUGINS -->\n");
      out.write("    <!-- BEGIN THEME GLOBAL STYLES -->\n");
      out.write("    <link href=\"");
      out.print(request.getContextPath() );
      out.write("/static/global/css/components.min.css\" rel=\"stylesheet\" id=\"style_components\" type=\"text/css\" />\n");
      out.write("\t<link href=\"");
      out.print(request.getContextPath() );
      out.write("/static/global/css/plugins.min.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("    <!-- END THEME GLOBAL STYLES -->\n");
      out.write("    <!-- BEGIN PAGE LEVEL STYLES -->\n");
      out.write("    <link href=\"");
      out.print(request.getContextPath() );
      out.write("/static/pages/css/login-2.min.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("    <!-- END PAGE LEVEL STYLES -->\n");
      out.write("\n");
      out.write("\t<link rel=\"shortcut icon\" href=\"");
      out.print(request.getContextPath());
      out.write("/portal/image/itzixi_favicon.ico\" type=\"image/x-icon\">\n");
      out.write("        \n");
      out.write("\t<style type=\"text/css\">\n");
      out.write("\t\t.help-block {\n");
      out.write("\t\t\tdisplay: block;\n");
      out.write("\t\t  \tmargin-top: 5px;\n");
      out.write("\t\t  \tmargin-bottom: 10px;\n");
      out.write("\t\t  \tcolor: red; \n");
      out.write("\t\t}\n");
      out.write("\t</style>\n");
      out.write("\t\n");
      out.write("</head>\n");
      out.write("<body class=\"login\">\n");
      out.write("        <!-- BEGIN LOGO -->\n");
      out.write("        <div class=\"logo\">\n");
      out.write("            <a href=\"");
      out.print(request.getContextPath());
      out.write("/\">\n");
      out.write("                <img src=\"");
      out.print(request.getContextPath());
      out.write("/static/pages/img/logos/logo.png\" /> \n");
      out.write("            </a>\n");
      out.write("        </div>\n");
      out.write("        <!-- END LOGO -->\n");
      out.write("        <!-- BEGIN LOGIN -->\n");
      out.write("        <div class=\"content\">\n");
      out.write("            <!-- BEGIN LOGIN FORM -->\n");
      out.write("            <form class=\"login-form\">\n");
      out.write("\n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                    <!--ie8, ie9 does not support html5 placeholder, so we just show field title for that-->\n");
      out.write("                    <label class=\"control-label visible-ie8 visible-ie9\">用户名</label>\n");
      out.write("                    <div id=\"input-error\">\n");
      out.write("                    \t<input class=\"form-control form-control-solid placeholder-no-fix\" type=\"text\" autocomplete=\"off\" placeholder=\"用户名\" name=\"username\" /> </div>\n");
      out.write("                    </div>\n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                    <label class=\"control-label visible-ie8 visible-ie9\">密码</label>\n");
      out.write("                    <div id=\"input-error\">\n");
      out.write("                    \t<input class=\"form-control form-control-solid placeholder-no-fix\" type=\"password\" autocomplete=\"off\" placeholder=\"密码\" name=\"password\" /> </div>\n");
      out.write("                    </div>\n");
      out.write("                \n");
      out.write("                \n");
      out.write("                <div class=\"form-actions\" style=\"padding: 0 30px 15px;\">\n");
      out.write("                    <button type=\"submit\" class=\"btn red btn-block uppercase\">登 录</button>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"create-account\">\n");
      out.write("                    <p>\n");
      out.write("                        <a href=\"javascript:;\" class=\"btn-primary btn\" id=\"register-btn\">注 册 用 户</a>\n");
      out.write("                    </p>\n");
      out.write("                </div>\n");
      out.write("            </form>\n");
      out.write("            <!-- END LOGIN FORM -->\n");
      out.write("\n");
      out.write("            <!-- BEGIN REGISTRATION FORM -->\n");
      out.write("            <form class=\"register-form\">\n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                    <label class=\"control-label visible-ie8 visible-ie9\">用户名</label>\n");
      out.write("                    <div id=\"input-error\">\n");
      out.write("                    \t<input class=\"form-control placeholder-no-fix\" type=\"text\" placeholder=\"用户名\" name=\"username\" />\n");
      out.write("                    </div> \n");
      out.write("                </div>\n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                    <label class=\"control-label visible-ie8 visible-ie9\">密码</label>\n");
      out.write("                    <div id=\"input-error\">\n");
      out.write("                    \t<input class=\"form-control placeholder-no-fix\" type=\"text\" placeholder=\"密码\" name=\"password\" />\n");
      out.write("                    </div> \n");
      out.write("                </div>\n");
      out.write("                <div class=\"form-actions\">\n");
      out.write("                    <button type=\"button\" id=\"register-back-btn\" class=\"btn btn-default\">返 回</button>\n");
      out.write("                </div>\n");
      out.write("            </form>\n");
      out.write("            <!-- END REGISTRATION FORM -->\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <input type=\"hidden\" id=\"hdnContextPath\" name=\"hdnContextPath\" value=\"");
      out.print(request.getContextPath() );
      out.write("\"/>\n");
      out.write("        \n");
      out.write("<!--[if lt IE 9]>\n");
      out.write("<script src=\"../assets/global/plugins/respond.min.js?v=3.1415926\"></script>\n");
      out.write("<script src=\"../assets/global/plugins/excanvas.min.js?v=3.1415926\"></script> \n");
      out.write("<script src=\"../assets/global/plugins/ie8.fix.min.js?v=3.1415926\"></script> \n");
      out.write("<![endif]-->\n");
      out.write("        \n");
      out.write("        <!-- 公用尾部JS start -->\n");
      out.write("\t    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "common/commonFooterJS.jsp", out, false);
      out.write("\n");
      out.write("\t    <!-- 公用尾部JS end -->\n");
      out.write("    \n");
      out.write("        <script src=\"");
      out.print(request.getContextPath() );
      out.write("/static/pages/js/login.js?v=1.1\" type=\"text/javascript\"></script>\n");
      out.write("        \n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
